### ISSUE TITLE
[LOW] add questions with images

### ISSUE THREAD

**Issue by MrSnake85** [SamboyCoding/KrystaraBot#10]
**LOW PRIORITY**

please create questions with images for the first quiz update (later)

use every available image type
- kingdoms
- banners
- troops
- classes

**Comment by SamboyCoding** [comment]
In progress right now

**Comment by Lyya** [comment]
Shields/Banners are completed, as are Spells.  Troops/Classes might be too easy?

**Comment by MrSnake85** [comment]
troops are not this easy as you may think... there are a bunch of troops you face every time in pvp - but there are a lot more you dont use/see regularly and where you dont know the names

also most people dont run a website with a troop database ;)

class logos are the same - you dont get to see them very often

**Comment by Lyya** [comment]
Troops/Classes now implemented and committed.  They're currently in the "Unused" difficulty; we should assess and categorize after playing with them in the quiz.

**Comment by SamboyCoding** [comment]
Ok, i'm closing this then.
