### ISSUE TITLE
[LOW] remove muted role

### ISSUE THREAD

**Issue by MrSnake85** [SamboyCoding/KrystaraBot#2]
**LOW PRIORITY**

remove the muted role from live and test channels because we wont use it 
- remove role from live server
- remove muted-appela channel
- remove from ?serverstats command (and maybe other occuring commands)

**Comment by SamboyCoding** [comment]
Removing the role from the server will remove it from serverstats.

**Comment by SamboyCoding** [comment]
Thanks for that.

**Comment by MrSnake85** [comment]
## reopen ##

issue not resolved - so ticket not closed^^

**Comment by SamboyCoding** [comment]
I thought i removed it? It was still on live server but that's yours. I just searched the entire bot for the word "Muted" but it's not there. Closing. LEAVE IT CLOSED THIS TIME.
